language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
  - release
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - npm run prodbuild
  - ./node_modules/.bin/prettier-check src/**/*.ts
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/tracker
  fqdn: cidsworkshop.com
  on:
    branch: release